package Kap9;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class JavaUebung09 extends JFrame {
    private JButton uebernehmen;
    private JButton ende;
    private JLabel labelStunden;
    private JLabel labelMinuten;
    private JPanel Uhrzeit;
    private JTextField fieldStunden;
    private JTextField fieldMinuten;
    private JLabel ausgabe;


    public JavaUebung09() {
        setTitle("Uhrzeit");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 200);
        setLocationRelativeTo(null);
        setVisible(true);
        setContentPane(Uhrzeit);


        uebernehmen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String stunden = fieldStunden.getText();
                    String minuten = fieldMinuten.getText();
                    int stundenergebnis = Integer.parseInt(stunden);
                    int minutenergebnis = Integer.parseInt(minuten);

                    String ausgabe1 = "Ihre Uhrzeit ist " + stunden + ":" + minuten + " Uhr.";

                    ausgabe.setText(ausgabe1);

                    if (stundenergebnis < 0 || stundenergebnis > 23) {
                        throw new StundenPruefer();
                    }

                    if (minutenergebnis < 0 || minutenergebnis > 59) {
                        throw new MinutenPruefer();
                    }

                } catch (StundenPruefer ex) {

                    ausgabe.setText("Stundeneingabe ist Falsch!");

                } catch (MinutenPruefer ey) {

                    ausgabe.setText("Minuteneingabe ist Falsch!");

                }


            }
        });
    }


    public static void main(String[] args) {
        new JavaUebung09();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Uhrzeit = new JPanel();
        Uhrzeit.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        labelMinuten = new JLabel();
        labelMinuten.setText("Minuten");
        Uhrzeit.add(labelMinuten, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ausgabe = new JLabel();
        ausgabe.setText("Ihre Uhrzeit ist __ Uhr..");
        Uhrzeit.add(ausgabe, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        uebernehmen = new JButton();
        uebernehmen.setText("Übernehmen");
        Uhrzeit.add(uebernehmen, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ende = new JButton();
        ende.setText("Ende");
        Uhrzeit.add(ende, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelStunden = new JLabel();
        labelStunden.setText("Stunden");
        Uhrzeit.add(labelStunden, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldStunden = new JTextField();
        Uhrzeit.add(fieldStunden, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fieldMinuten = new JTextField();
        Uhrzeit.add(fieldMinuten, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Uhrzeit;
    }

}
